### ISSUE TITLE
Tried to compile the example

### ISSUE THREAD

**Issue by f15radar** [younatics/MediaBrowser#3]
I received a lot of compile errors and it tried to convert to swift 3? Why does it convert when its written in swift 3.  Thanks.

**Comment by rhinodavid** [comment]
Hi -- I may be having a similar problem. Here's some more information:

Steps to repo:
- Clone the repository
- Delete `ALWAYS_REMOVE_SWIFT_STANDARD_LIBRARIES` from the build settings for Debug/Release of the Demo app. Otherwise I get an error when installing the Pods
- Run `pod install`
- In XCode, select the `MediaBrowser` library as the build target and run build

Expected outcome:
Build succeeds

Actual outcome:
Build fails with the following error:
<img width="611" alt="screen shot 2017-09-10 at 12 55 10 pm" src="https://user-images.githubusercontent.com/5778036/30251577-0855e3ee-9628-11e7-91de-bc6494d9ff9b.png">

**Comment by jegumhon** [comment]
This example is using the cocoapods. So, you should open the MediaBrowser.xcworkspace to run or test the example.
Also, the example is wrriten in Swift3. You don't need to convert them.
Thanks.

**Comment by unittesting0** [comment]
I'm having the same issue as OP.

**Comment by younatics** [comment]
Hello @unittesting0  Did you try `pod install`?

**Comment by f15radar** [comment]
Sorry, I have been off the grid thanks to hurricane Irma.  I ended up doing a pod install and then going in and setting the default language to Swift 3.  I then got it to compile the example.  Next I will try and use it in my app.

**Comment by jegumhon** [comment]
@f15radar Irma!!? 😢 Oh, god! I'm glad you're O.K.
After trying, if you have any issues or opinions, let us know!!
Thanks!
